export const FRONTEND_LABELS = {
  lblNavHome: { en: "HOME", ar: "الرئيسية" },
  lblNavCakes: { en: "CAKES", ar: "الكيك" },
  lblNavIceCreams: { en: "ICE CREAMS", ar: "الآيس كريم" },
  lblNavCookies: { en: "COOKIES", ar: "الكوكيز" },
  lblNavDiy: { en: "DIY", ar: "اصنعها بنفسك" },
  lblNavOccasions: { en: "OCCASIONS", ar: "المناسبات" },

  lblLogoAlt: { en: "Marble Slab", ar: "ماربل سلاب" },
  lblSearchPlaceholder: { en: "Search", ar: "بحث" },
  lblMainNavigation: { en: "Main navigation", ar: "التنقل الرئيسي" },
  lblSearchProducts: { en: "Search products", ar: "البحث عن المنتجات" },
  lblClearSearch: { en: "Clear search", ar: "مسح البحث" },
  lblSearchResultsFor: { en: "Search results for", ar: "نتائج البحث عن" },
  lblSearchResultsCount: {
    en: "{count} products found",
    ar: "تم العثور على {count} منتجات",
  },
  lblSearchEnterQuery: {
    en: "Enter a product name in the search box above.",
    ar: "أدخل اسم المنتج في مربع البحث أعلاه.",
  },
  lblSearchLoadError: {
    en: "Search could not be completed. Please try again.",
    ar: "تعذر إكمال البحث. يرجى المحاولة مرة أخرى.",
  },
  lblSearchTryAgain: {
    en: "Try a different spelling or browse cakes and ice creams.",
    ar: "جرّب كتابة أخرى أو تصفح الكيك والآيس كريم.",
  },
  lblMyAccount: { en: "My account", ar: "حسابي" },
  lblLogout: { en: "Logout", ar: "تسجيل الخروج" },
  lblUserAccount: { en: "User account", ar: "حساب المستخدم" },
  lblShoppingCart: { en: "Shopping cart", ar: "سلة التسوق" },
  lblOpenMenu: { en: "Open menu", ar: "فتح القائمة" },
  lblClose: { en: "Close", ar: "إغلاق" },
  lblQuickLinks: { en: "Quick Links", ar: "روابط سريعة" },
  lblAboutUs: { en: "About Us", ar: "من نحن" },
  lblAbout: { en: "About", ar: "من نحن" },
  lblContact: { en: "Contact", ar: "اتصل بنا" },
  lblFaq: { en: "FAQ", ar: "الأسئلة الشائعة" },
  lblFrequentlyAskQuestions: {
    en: "Frequently Ask Questions",
    ar: "الأسئلة المتكررة",
  },
  lblNoFaqs: {
    en: "No FAQs available right now.",
    ar: "لا توجد أسئلة شائعة حالياً.",
  },
  lblCustomerHotline: { en: "Customer hotline", ar: "خط خدمة العملاء" },
  lblWhatsapp: { en: "WhatsApp", ar: "واتساب" },
  lblEmail: { en: "E-mail", ar: "البريد الإلكتروني" },
  lblVisitUs: { en: "Visit us", ar: "زورونا" },
  lblOurStoresIn: { en: "Our Stores in", ar: "فروعنا في" },
  lblJeddah: { en: "Jeddah", ar: "جدة" },

  lblCollection: { en: "Collection", ar: "المجموعة" },
  lblReadyCakes: { en: "Ready Cakes", ar: "كيك جاهز" },
  lblCookieBox: { en: "Cookie Box", ar: "علبة كوكيز" },
  lblServices: { en: "Services", ar: "الخدمات" },
  lblCustomCake: { en: "Custom Cake", ar: "كيك مخصص" },
  lblCustomIceCream: { en: "Custom Ice Cream", ar: "آيس كريم مخصص" },
  lblMarbleVan: { en: "Marble Van", ar: "ماربل فان" },
  lblCompany: { en: "Company", ar: "الشركة" },
  lblContactUs: { en: "Contact us", ar: "تواصل معنا" },
  lblCallUs: { en: "Call us", ar: "اتصل بنا" },
  lblWhatsappUs: { en: "WhatsApp us", ar: "راسلنا واتساب" },
  lblEmailUs: { en: "Email us", ar: "راسلنا بالبريد" },
  lblFollowUs: { en: "Follow us", ar: "تابعنا" },
  lblLanguage: { en: "Language", ar: "اللغة" },
  lblSwitchLanguageTo: { en: "Switch language to", ar: "تغيير اللغة إلى" },
  lblInstagram: { en: "Instagram", ar: "إنستغرام" },
  lblFacebook: { en: "Facebook", ar: "فيسبوك" },
  lblTiktok: { en: "TikTok", ar: "تيك توك" },
  lblCopyright: {
    en: "© 2025 Marble Slab. All Rights Reserved.",
    ar: "© 2025 ماربل سلاب. جميع الحقوق محفوظة.",
  },
  lblPrivacyPolicy: { en: "Privacy Policy", ar: "سياسة الخصوصية" },

  lblLoginStarted: { en: "Let's get started", ar: "لنبدأ" },
  lblLogin: { en: "Log in", ar: "تسجيل الدخول" },
  lblSignup: { en: "Sign up", ar: "إنشاء حساب" },
  lblEnterName: { en: "Enter Your Name", ar: "أدخل اسمك" },
  lblEnterPhone: { en: "Enter Your Phone Number", ar: "أدخل رقم هاتفك" },
  lblEnterPassword: { en: "Enter Your Password", ar: "أدخل كلمة المرور" },
  lblPhoneNumber: { en: "Phone number", ar: "رقم الهاتف" },
  lblFullName: { en: "Full name", ar: "الاسم الكامل" },
  lblPassword: { en: "Password", ar: "كلمة المرور" },
  lblContinue: { en: "Continue", ar: "متابعة" },
  lblLoading: { en: "Loading...", ar: "جار التحميل..." },
  lblRequiredFields: { en: "Please fill in all fields", ar: "يرجى تعبئة جميع الحقول" },
  lblInvalidLogin: { en: "Invalid phone number or password", ar: "رقم الهاتف أو كلمة المرور غير صحيحة" },
  lblErrorOccurred: { en: "Error occurred", ar: "حدث خطأ" },

  lblOccasionsTitle: { en: "Occasions", ar: "المناسبات" },
  lblOccasionsSubtitle: { en: "Choose your special case", ar: "اختر مناسبتك الخاصة" },
  lblClearSelection: { en: "Clear selection", ar: "مسح الاختيار" },
  lblApply: { en: "Apply", ar: "تطبيق" },
  lblFilters: { en: "Filters", ar: "الفلاتر" },
  lblCakeType: { en: "Cake Type", ar: "نوع الكيك" },
  lblPortionSize: { en: "Portion Size", ar: "حجم الحصة" },
  lblFor: { en: "For", ar: "مناسب لـ" },
  lblResetFilters: { en: "Reset Filters", ar: "إعادة ضبط الفلاتر" },
  lblNoPortionSizesFound: { en: "No portion sizes found.", ar: "لا توجد أحجام حصص." },
  lblNoProductsFound: { en: "No product found", ar: "لم يتم العثور على منتجات" },
  lblNoProductsFoundAlt: { en: "No products found", ar: "لم يتم العثور على منتجات" },
  lblCakesBannerAlt: { en: "Cakes banner", ar: "بانر الكيك" },
  lblIceCreamBannerAlt: { en: "Ice cream banner", ar: "بانر الآيس كريم" },
  lblCustomizeCake: { en: "Customize Your Own Cake", ar: "صمم كيكك بنفسك" },
  lblMakeItYourWay: { en: "Make it your way", ar: "اصنعها بطريقتك" },
  lblCustomizeCakeAlt: { en: "Customize your own cake", ar: "صمم كيكك بنفسك" },
  lblStartCustomCake: { en: "Start Custom Cake", ar: "ابدأ تصميم الكيك" },
  lblCustomizeIceCream: { en: "Customize Your Own Ice Cream", ar: "صمم الآيس كريم الخاص بك" },
  lblIceCreamCustomizationMeta: {
    en: "Choose bucket, flavors, mixins and sauces",
    ar: "اختر الدلو والنكهات والإضافات والصلصات",
  },
  lblCustomizeIceCreamAlt: { en: "Customize your own ice cream", ar: "صمم الآيس كريم الخاص بك" },
  lblStartCustomIceCream: { en: "Start Custom Ice Cream", ar: "ابدأ تصميم الآيس كريم" },
  lblProductNotFound: { en: "Product not found", ar: "لم يتم العثور على المنتج" },
  lblNotAvailable: { en: "N/A", ar: "غير متوفر" },
  lblSelectSize: { en: "Select Size", ar: "اختر الحجم" },
  lblSelectFlavor: { en: "Select Flavor", ar: "اختر النكهة" },
  lblSelectPortionSize: { en: "Select Portion Size", ar: "اختر حجم الحصة" },
  lblCalories: { en: "Calories", ar: "السعرات الحرارية" },
  lblAddTextToCake: { en: "Add Text to Cake", ar: "أضف نصاً على الكيك" },
  lblCakeTextPlaceholder: { en: "e.g. Happy Birthday Sarah", ar: "مثال: عيد ميلاد سعيد سارة" },
  lblAdditionalNote: { en: "Additional Note", ar: "ملاحظة إضافية" },
  lblSpecialInstructions: { en: "Special instructions...", ar: "تعليمات خاصة..." },
  lblAddingToCart: { en: "Adding...", ar: "جار الإضافة..." },
  lblDecreaseQuantity: { en: "Decrease quantity", ar: "تقليل الكمية" },
  lblIncreaseQuantity: { en: "Increase quantity", ar: "زيادة الكمية" },
  lblDescription: { en: "Description", ar: "الوصف" },
  lblAllergens: { en: "Allergens", ar: "مسببات الحساسية" },
  lblNoDescriptionAvailable: { en: "No description available", ar: "لا يوجد وصف متاح" },
  lblCalorieInformationUnavailable: {
    en: "Calorie information not available",
    ar: "معلومات السعرات الحرارية غير متوفرة",
  },
  lblAllergenInformationUnavailable: {
    en: "Allergen information not available",
    ar: "معلومات مسببات الحساسية غير متوفرة",
  },
  lblYouMayAlsoLike: { en: "You may also like", ar: "قد يعجبك أيضاً" },
  lblBackToCakes: { en: "Back to cakes", ar: "العودة إلى الكيك" },
  lblBackToIceCreams: { en: "Back to ice creams", ar: "العودة إلى الآيس كريم" },
  lblIceCreamBucket: { en: "Ice Cream Bucket", ar: "دلو الآيس كريم" },
  lblIceCreamBucketBannerAlt: { en: "Ice cream bucket banner", ar: "بانر دلو الآيس كريم" },
  lblSelectBucketSize: { en: "Select bucket size", ar: "اختر حجم الدلو" },
  lblSelectUpToTwoFlavors: { en: "Select up to 2 flavors", ar: "اختر حتى نكهتين" },
  lblChooseMixins: { en: "Choose mix-ins", ar: "اختر الإضافات" },
  lblFreeMixinsNote: {
    en: "Your first two mix-ins are FREE. After that, enjoy additional mix-ins for SR.4 each",
    ar: "أول إضافتين مجاناً. بعد ذلك يمكنك إضافة المزيد مقابل 4 ريال لكل إضافة",
  },
  lblAdditionalCharge: { en: "Additional charge", ar: "رسوم إضافية" },
  lblChooseSpecialSauces: { en: "Choose special sauces", ar: "اختر الصلصات الخاصة" },
  lblOptional: { en: "Optional", ar: "اختياري" },
  lblEachSauce: { en: "Each sauce SR.6", ar: "كل صلصة 6 ريال" },
  lblBucketSize: { en: "Bucket size", ar: "حجم الدلو" },
  lblFlavors: { en: "Flavors", ar: "النكهات" },
  lblMixins: { en: "Mix-ins", ar: "الإضافات" },
  lblSauces: { en: "Sauces", ar: "الصلصات" },
  lblSubtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  lblCustomIceCreamUnavailable: {
    en: "Custom ice cream product is not available.",
    ar: "منتج الآيس كريم المخصص غير متوفر.",
  },
  lblSelectBucketSizeError: { en: "Please select a bucket size.", ar: "يرجى اختيار حجم الدلو." },
  lblSelectUpToTwoFlavorsError: { en: "Please select up to 2 flavors.", ar: "يرجى اختيار حتى نكهتين." },
  lblSelectUpToNineMixinsError: { en: "Please select up to 9 mix-ins.", ar: "يرجى اختيار حتى 9 إضافات." },
  lblSelectUpToTwoFlavorsDetailedError: {
    en: "You can select up to 2 flavors. Please deselect a flavor before selecting another one.",
    ar: "يمكنك اختيار نكهتين فقط. يرجى إلغاء اختيار نكهة قبل اختيار أخرى.",
  },
  lblSelectUpToNineMixinsDetailedError: {
    en: "You can select up to 9 mix-ins.",
    ar: "يمكنك اختيار حتى 9 إضافات.",
  },
  lblCustomIceCreamAddError: {
    en: "Unable to add custom ice cream to cart. Please try again.",
    ar: "تعذرت إضافة الآيس كريم المخصص إلى السلة. يرجى المحاولة مرة أخرى.",
  },
  lblDesignCakeBannerAlt: { en: "Design your cake banner", ar: "بانر تصميم الكيك" },
  lblCustomiseYourOwnCake: { en: "Customise your own Cake", ar: "صمم كيكك بنفسك" },
  lblSelectCakeType: { en: "Select cake type", ar: "اختر نوع الكيك" },
  lblSelectCakeSize: { en: "Select cake size", ar: "اختر حجم الكيك" },
  lblSelectCakeFlavor: { en: "Select cake flavor", ar: "اختر نكهة الكيك" },
  lblAddSketchPhotos: { en: "Add your sketch / photos", ar: "أضف الرسم أو الصور" },
  lblMaxSize: { en: "Max size: 5MB", ar: "الحد الأقصى: 5 ميجابايت" },
  lblUploadSketchImage: { en: "Upload your sketch image", ar: "ارفع صورة الرسم" },
  lblAllowedImageTypes: { en: "Allowed: .jpg .jpeg .png .gif", ar: "المسموح: .jpg .jpeg .png .gif" },
  lblAddCakeText: { en: "Add cake text", ar: "أضف نص الكيك" },
  lblYourTextForCake: { en: "Your text for cake", ar: "النص المطلوب على الكيك" },
  lblColorOfText: { en: "Color of text", ar: "لون النص" },
  lblColorOfBorder: { en: "Color of border", ar: "لون الإطار" },
  lblYourAdditionalNote: { en: "Your additional note", ar: "ملاحظتك الإضافية" },
  lblSummary: { en: "Summary", ar: "الملخص" },
  lblCakeText: { en: "Cake text", ar: "نص الكيك" },
  lblColorText: { en: "Color text", ar: "لون النص" },
  lblBorderColor: { en: "Border color", ar: "لون الإطار" },
  lblCakeNote: { en: "Cake note", ar: "ملاحظة الكيك" },
  lblGetQuote: { en: "Get a Quote", ar: "اطلب عرض سعر" },
  lblSubmitting: { en: "Submitting...", ar: "جار الإرسال..." },
  lblCustomCakeUnavailable: {
    en: "Custom cake product is not available.",
    ar: "منتج الكيك المخصص غير متوفر.",
  },
  lblSelectCakeTypeError: { en: "Please select cake type.", ar: "يرجى اختيار نوع الكيك." },
  lblSelectCakeSizeError: { en: "Please select cake size.", ar: "يرجى اختيار حجم الكيك." },
  lblSelectCakeFlavorError: { en: "Please select cake flavor.", ar: "يرجى اختيار نكهة الكيك." },
  lblLoginBeforeQuote: {
    en: "Please login before requesting a quotation.",
    ar: "يرجى تسجيل الدخول قبل طلب عرض السعر.",
  },
  lblQuoteSubmitError: { en: "Unable to submit quote request.", ar: "تعذر إرسال طلب عرض السعر." },
  lblSketchTooLarge: { en: "Sketch image must be 5MB or smaller.", ar: "يجب ألا تتجاوز صورة الرسم 5 ميجابايت." },
  lblCartEmptiedSuccessfully: { en: "Cart emptied successfully", ar: "تم إفراغ السلة بنجاح" },
  lblContinueShopping: { en: "Continue shopping", ar: "متابعة التسوق" },
  lblMyCart: { en: "My Cart", ar: "سلتي" },
  lblCouponCode: { en: "Coupon code", ar: "رمز القسيمة" },
  lblApplyCoupon: { en: "Apply coupon", ar: "تطبيق القسيمة" },
  lblRemoveCoupon: { en: "Remove coupon", ar: "إزالة القسيمة" },
  lblCouponApplied: { en: "Coupon applied successfully.", ar: "تم تطبيق القسيمة بنجاح." },
  lblCouponRemoved: { en: "Coupon removed.", ar: "تمت إزالة القسيمة." },
  lblCouponInvalid: { en: "Unable to apply this coupon.", ar: "تعذر تطبيق هذه القسيمة." },
  lblCouponRemoveFailed: { en: "Unable to remove this coupon.", ar: "تعذر إزالة هذه القسيمة." },
  lblUpdateCart: { en: "Update cart", ar: "تحديث السلة" },
  lblEmptyCartAlt: { en: "Empty cart", ar: "سلة فارغة" },
  lblEmptyCartTitle: { en: "There are no items yet", ar: "لا توجد عناصر بعد" },
  lblEmptyCartSubtitle: { en: "Add something to make me happy", ar: "أضف شيئاً لتجعلني سعيداً" },
  lblViewCatalog: { en: "View catalog", ar: "عرض الكتالوج" },
  lblRemoveItem: { en: "Remove item", ar: "إزالة العنصر" },
  lblEmptyCart: { en: "Empty cart", ar: "إفراغ السلة" },
  lblTotal: { en: "Total", ar: "الإجمالي" },
  lblProceedToCheckout: { en: "Proceed to checkout", ar: "المتابعة إلى الدفع" },
  lblAddOnsItems: { en: "Add ons Items", ar: "الإضافات" },
  lblCakeSize: { en: "Cake Size", ar: "حجم الكيك" },
  lblCakeFlavor: { en: "Cake Flavor", ar: "نكهة الكيك" },
  lblBoxType: { en: "Box Type", ar: "نوع العلبة" },
  lblBoxSize: { en: "Box Size", ar: "حجم العلبة" },
  lblCookies: { en: "Cookies", ar: "الكوكيز" },
  lblText: { en: "Text", ar: "النص" },
  lblNote: { en: "Note", ar: "ملاحظة" },
  lblSketch: { en: "Sketch", ar: "الرسم" },
  lblUploaded: { en: "Uploaded", ar: "تم الرفع" },
  lblPieceShort: { en: "pc.", ar: "قطعة" },
  lblCheckout: { en: "Checkout", ar: "الدفع" },
  lblBackToCart: { en: "Back to cart", ar: "العودة إلى السلة" },
  lblYourCartIsEmpty: { en: "Your cart is empty.", ar: "سلتك فارغة." },
  lblReceiving: { en: "Receiving", ar: "الاستلام" },
  lblDelivery: { en: "Delivery", ar: "توصيل" },
  lblPickup: { en: "Pickup", ar: "استلام" },
  lblDeliveryDetails: { en: "Delivery details", ar: "تفاصيل التوصيل" },
  lblPickupDetails: { en: "Pickup details", ar: "تفاصيل الاستلام" },
  lblSelectReceivingType: { en: "Select receiving type", ar: "اختر نوع الاستلام" },
  lblEdit: { en: "Edit", ar: "تعديل" },
  lblAdd: { en: "Add", ar: "إضافة" },
  lblAddress: { en: "Address", ar: "العنوان" },
  lblCity: { en: "City", ar: "المدينة" },
  lblBranch: { en: "Branch", ar: "الفرع" },
  lblTimeSlot: { en: "Time slot", ar: "الفترة الزمنية" },
  lblDate: { en: "Date", ar: "التاريخ" },
  lblSenderInfo: { en: "Sender Info", ar: "بيانات المرسل" },
  lblRecipientData: { en: "Recipient Data", ar: "بيانات المستلم" },
  lblPhone: { en: "Phone", ar: "الهاتف" },
  lblLoginRequiredCheckout: { en: "You must login before checkout.", ar: "يجب تسجيل الدخول قبل الدفع." },
  lblLoginRegister: { en: "Login / Register", ar: "تسجيل الدخول / إنشاء حساب" },
  lblRecipientsInfo: { en: "Recipient's Info", ar: "بيانات المستلم" },
  lblRecipientName: { en: "Recipient Name", ar: "اسم المستلم" },
  lblRecipientPhone: { en: "Recipient Phone", ar: "هاتف المستلم" },
  lblShippingCost: { en: "Shipping Cost", ar: "تكلفة الشحن" },
  lblFreeDelivery: { en: "Free delivery", ar: "توصيل مجاني" },
  lblFree: { en: "Free", ar: "مجاني" },
  lblChooseFreeProduct: { en: "Choose your free product", ar: "اختر منتجك المجاني" },
  lblFreeProductSelected: { en: "Free product added to your cart.", ar: "تمت إضافة المنتج المجاني إلى سلتك." },
  lblUnableLoadShippingSettings: {
    en: "Unable to load delivery fee settings. Please try again.",
    ar: "تعذر تحميل إعدادات رسوم التوصيل. يرجى المحاولة مرة أخرى.",
  },
  lblTax: { en: "Tax", ar: "الضريبة" },
  lblDirectBankTransfer: { en: "Direct bank transfer", ar: "تحويل بنكي مباشر" },
  lblBankTransferDescription: {
    en: "Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.",
    ar: "حوّل المبلغ مباشرة إلى حسابنا البنكي. يرجى استخدام رقم الطلب كمرجع للدفع. لن يتم شحن طلبك حتى يتم تأكيد وصول المبلغ إلى حسابنا.",
  },
  lblCashOnDelivery: { en: "Cash on delivery", ar: "الدفع عند الاستلام" },
  lblExpiredTimeSlot: {
    en: "Your selected time slot has expired. Please choose another slot.",
    ar: "انتهت صلاحية الفترة الزمنية المحددة. يرجى اختيار فترة أخرى.",
  },
  lblPlacingOrder: { en: "Placing order...", ar: "جار تنفيذ الطلب..." },
  lblPlaceOrder: { en: "Place order", ar: "تنفيذ الطلب" },
  lblOrderPrivacyNotice: {
    en: "Your personal data will be used to process your order and support your experience.",
    ar: "سيتم استخدام بياناتك الشخصية لمعالجة طلبك ودعم تجربتك.",
  },
  lblDiscount: { en: "Discount", ar: "الخصم" },
  lblEnterPromoCode: { en: "Enter promo code", ar: "أدخل رمز العرض" },
  lblCoupon: { en: "Coupon", ar: "القسيمة" },
  lblEnterFullNameError: { en: "Please enter your full name.", ar: "يرجى إدخال الاسم الكامل." },
  lblValidPhoneError: { en: "Please enter a valid 9-digit phone number.", ar: "يرجى إدخال رقم هاتف صحيح من 9 أرقام." },
  lblLoginBeforeOrder: {
    en: "Please login or register before placing your order.",
    ar: "يرجى تسجيل الدخول أو إنشاء حساب قبل تنفيذ الطلب.",
  },
  lblCreateOrderError: { en: "Unable to create order.", ar: "تعذر إنشاء الطلب." },
  lblSendForSomeone: { en: "Send for someone", ar: "إرسال لشخص آخر" },
  lblIHaveAddress: { en: "I have address", ar: "لدي عنوان" },
  lblIDontHaveAddress: { en: "I don't have address", ar: "ليس لدي عنوان" },
  lblSearchAddress: { en: "Search Address", ar: "ابحث عن العنوان" },
  lblAddressLine: { en: "Address line", ar: "سطر العنوان" },
  lblSelectCity: { en: "Select city", ar: "اختر المدينة" },
  lblChooseStore: { en: "Choose store", ar: "اختر المتجر" },
  lblSelectStore: { en: "Select store", ar: "اختر المتجر" },
  lblChooseDateTimeSlot: { en: "Choose date and time slot", ar: "اختر التاريخ والفترة الزمنية" },
  lblSelectTime: { en: "Select Time", ar: "اختر الوقت" },
  lblSaveSettings: { en: "Save settings", ar: "حفظ الإعدادات" },
  lblPickupOnlyProduct: {
    en: "This item is available for pickup only.",
    ar: "هذا المنتج متاح للاستلام من الفرع فقط.",
  },
  lblReceivingUnavailable: {
    en: "Pickup and delivery are currently unavailable.",
    ar: "الاستلام والتوصيل غير متاحين حالياً.",
  },
  lblTimeSlotsLoadError: {
    en: "Time slots could not be loaded. Please try again.",
    ar: "تعذر تحميل الفترات الزمنية. يرجى المحاولة مرة أخرى.",
  },
  lblSpecialDayDateLocked: {
    en: "This product can only be received on the selected special day.",
    ar: "يمكن استلام هذا المنتج فقط في اليوم الخاص المحدد.",
  },
  lblPreOrdersOpenFrom: {
    en: "Pre-orders open from",
    ar: "الطلبات المسبقة متاحة من",
  },
  lblTo: { en: "to", ar: "إلى" },
  lblAnd: { en: "and", ar: "و" },
  lblReserveYoursNow: {
    en: "! Reserve yours now",
    ar: "! احجز الآن",
  },
  lblSpecialDayUnavailableBetween: {
    en: "This product will be available between",
    ar: "هذا المنتج سيكون متاحاً بين",
  },
  lblDateRequired: { en: "Date is required.", ar: "التاريخ مطلوب." },
  lblTimeSlotRequired: { en: "Time slot is required.", ar: "الفترة الزمنية مطلوبة." },
  lblRecipientNameRequired: { en: "Recipient name is required.", ar: "اسم المستلم مطلوب." },
  lblRecipientPhoneInvalid: {
    en: "Recipient phone must start with 9665 and contain 12 digits.",
    ar: "يجب أن يبدأ هاتف المستلم بـ 9665 ويتكون من 12 رقماً.",
  },
  lblAddressAvailabilityRequired: { en: "Please select address availability.", ar: "يرجى تحديد توفر العنوان." },
  lblDeliveryAddressRequired: { en: "Delivery address is required.", ar: "عنوان التوصيل مطلوب." },
  lblBranchNotSelected: { en: "Branch is not selected.", ar: "لم يتم اختيار الفرع." },
  lblBranchCityRequired: { en: "Branch city is required.", ar: "مدينة الفرع مطلوبة." },
  lblPickupBranchStoreRequired: { en: "Pickup branch store is required.", ar: "متجر فرع الاستلام مطلوب." },
  lblServiceUnavailableAddress: {
    en: "Sorry, service is not available for this address.",
    ar: "عذراً، الخدمة غير متوفرة لهذا العنوان.",
  },
  lblLocationAccessError: {
    en: "Allow location access or search your address on the map.",
    ar: "اسمح بالوصول إلى الموقع أو ابحث عن عنوانك على الخريطة.",
  },
  lblMapLoadError: { en: "Map could not be loaded.", ar: "تعذر تحميل الخريطة." },
  lblOrderReceivedPageTitle: { en: "Order Received | Marble Store", ar: "تم استلام الطلب | ماربل سلاب" },
  lblOrderNotFound: { en: "Sorry, Order not found", ar: "عذراً، لم يتم العثور على الطلب" },
  lblThankYou: { en: "Thank you", ar: "شكراً لك" },
  lblOrderPreparedMessage: {
    en: "Your order is #{orderNumber} and being prepared.",
    ar: "طلبك رقم #{orderNumber} قيد التحضير.",
  },
  lblContactHelpMessage: {
    en: "Don't hesitate to contact us if you need any help.",
    ar: "لا تتردد في التواصل معنا إذا احتجت إلى أي مساعدة.",
  },
  lblOrderNumber: { en: "Order number", ar: "رقم الطلب" },
  lblPaymentMethod: { en: "Payment method", ar: "طريقة الدفع" },
  lblQuotationRequest: { en: "Quotation request", ar: "طلب عرض سعر" },
  lblSeeMyOrders: { en: "See my orders", ar: "عرض طلباتي" },
  lblProfileInfo: { en: "Profile Info", ar: "معلومات الملف الشخصي" },
  lblOrdersHistory: { en: "Orders History", ar: "سجل الطلبات" },
  lblWishlist: { en: "Wishlist", ar: "قائمة المفضلة" },
  lblAddresses: { en: "Addresses", ar: "العناوين" },
  lblSettings: { en: "Settings", ar: "الإعدادات" },
  lblGuest: { en: "Guest", ar: "زائر" },
  lblMyAccountNavigation: { en: "My account navigation", ar: "تنقل حسابي" },
  lblUnableLoadOrders: { en: "Unable to load your orders right now.", ar: "تعذر تحميل طلباتك حالياً." },
  lblUnableLoadOrder: { en: "Unable to load this order right now.", ar: "تعذر تحميل هذا الطلب حالياً." },
  lblUnauthorizedOrder: { en: "You are not allowed to view this order.", ar: "غير مسموح لك بعرض هذا الطلب." },
  lblLoginToViewOrders: { en: "Please login to view your orders.", ar: "يرجى تسجيل الدخول لعرض طلباتك." },
  lblLoginToViewOrder: { en: "Please login to view this order.", ar: "يرجى تسجيل الدخول لعرض هذا الطلب." },
  lblNo: { en: "No", ar: "الرقم" },
  lblStatus: { en: "Status", ar: "الحالة" },
  lblItems: { en: "Items", ar: "العناصر" },
  lblActions: { en: "Actions", ar: "الإجراءات" },
  lblViewOrder: { en: "View Order", ar: "عرض الطلب" },
  lblOrderItemAlt: { en: "Order item", ar: "عنصر الطلب" },
  lblNoImage: { en: "No image", ar: "لا توجد صورة" },
  lblPayNow: { en: "Pay Now", ar: "ادفع الآن" },
  lblRejected: { en: "Rejected", ar: "مرفوض" },
  lblAccepted: { en: "Accepted", ar: "مقبول" },
  lblView: { en: "View", ar: "عرض" },
  lblNoOrdersYet: { en: "You have no orders yet.", ar: "ليس لديك طلبات بعد." },
  lblBrowseProducts: { en: "Browse Products", ar: "تصفح المنتجات" },
  lblOrderDate: { en: "Order Date", ar: "تاريخ الطلب" },
  lblBackToOrders: { en: "Back to orders", ar: "العودة إلى الطلبات" },
  lblOrderItems: { en: "Order Items", ar: "عناصر الطلب" },
  lblQuotationReady: { en: "Quotation ready", ar: "عرض السعر جاهز" },
  lblQuotationReadyDescription: {
    en: "Please accept the quotation to continue, or reject it if you do not want to proceed.",
    ar: "يرجى قبول عرض السعر للمتابعة، أو رفضه إذا كنت لا ترغب في الاستمرار.",
  },
  lblNoOptions: { en: "No options", ar: "لا توجد خيارات" },
  lblUnitPrice: { en: "Unit price", ar: "سعر الوحدة" },
  lblSketchPhoto: { en: "Sketch / photo", ar: "الرسم / الصورة" },
  lblCustomCakeSketchAlt: { en: "Custom cake sketch", ar: "رسم الكيك المخصص" },
  lblShipping: { en: "Shipping", ar: "الشحن" },
  lblAccept: { en: "Accept", ar: "قبول" },
  lblReject: { en: "Reject", ar: "رفض" },
  lblUnableLoadQuotation: { en: "Unable to load quotation.", ar: "تعذر تحميل عرض السعر." },
  lblQuotationMissingItem: {
    en: "Quotation is missing custom cake item or amount.",
    ar: "عرض السعر لا يحتوي على عنصر الكيك المخصص أو المبلغ.",
  },
  lblUnableAddQuotationToCart: {
    en: "Unable to add quotation to cart.",
    ar: "تعذرت إضافة عرض السعر إلى السلة.",
  },
  lblUnablePrepareCheckout: { en: "Unable to prepare checkout.", ar: "تعذر تجهيز الدفع." },
  lblUnableUpdateQuotation: { en: "Unable to update quotation.", ar: "تعذر تحديث عرض السعر." },
  lblUnableRejectQuotation: { en: "Unable to reject quotation.", ar: "تعذر رفض عرض السعر." },
  lblStatusPending: { en: "Pending payment", ar: "بانتظار الدفع" },
  lblStatusProcessing: { en: "Processing", ar: "قيد المعالجة" },
  lblStatusNewOrder: { en: "New order", ar: "طلب جديد" },
  lblStatusCustomCakeRequest: { en: "Custom cake request", ar: "طلب كيك مخصص" },
  lblStatusQuoteForApproval: { en: "Quote for approval", ar: "عرض سعر للموافقة" },
  lblStatusReadyToPickup: { en: "Ready to pickup", ar: "جاهز للاستلام" },
  lblStatusReadyToDeliver: { en: "Ready to deliver", ar: "جاهز للتوصيل" },
  lblStatusCompleted: { en: "Completed", ar: "مكتمل" },
  lblStatusCancelled: { en: "Cancelled", ar: "ملغي" },
  lblStatusRefunded: { en: "Refunded", ar: "مسترد" },
  lblStatusFailed: { en: "Failed", ar: "فشل" },
  lblCookiesBannerAlt: { en: "Cookies banner", ar: "بانر الكوكيز" },
  lblBack: { en: "Back", ar: "رجوع" },
  lblMakeYourOwnCookieBox: { en: "Make your own cookies box", ar: "اصنع علبة الكوكيز الخاصة بك" },
  lblSelectBoxType: { en: "Select box type", ar: "اختر نوع العلبة" },
  lblSelectBoxSize: { en: "Select box size", ar: "اختر حجم العلبة" },
  lblChooseCookies: { en: "Choose cookies", ar: "اختر الكوكيز" },
  lblCookiesSelected: { en: "selected", ar: "مختارة" },
  lblCookieProductUnavailable: { en: "Cookie product is not available.", ar: "منتج الكوكيز غير متوفر." },
  lblSelectBoxTypeError: { en: "Please select a box type.", ar: "يرجى اختيار نوع العلبة." },
  lblSelectBoxSizeError: { en: "Please select a box size.", ar: "يرجى اختيار حجم العلبة." },
  lblSelectExactCookiesError: {
    en: "Please select exactly {max} cookies, currently selected {count}.",
    ar: "يرجى اختيار {max} قطع كوكيز بالضبط، المحدد حالياً {count}.",
  },
  lblCannotExceedCookies: {
    en: "Cannot exceed {max} cookies for this box size.",
    ar: "لا يمكن تجاوز {max} قطع كوكيز لهذا الحجم.",
  },
  lblSelectUpToCookies: {
    en: "Select up to {max} cookies",
    ar: "اختر حتى {max} قطع كوكيز",
  },
  lblPieces: { en: "Pieces", ar: "قطع" },
  lblUnableAddCookiesToCart: {
    en: "Unable to add cookies to cart. Please try again.",
    ar: "تعذرت إضافة الكوكيز إلى السلة. يرجى المحاولة مرة أخرى.",
  },
  lblMyWishlist: { en: "My Wishlist", ar: "قائمة المفضلة" },
  lblLoginToViewProfile: { en: "Please login to view your profile.", ar: "يرجى تسجيل الدخول لعرض ملفك الشخصي." },
  lblPhoneNumberTitle: { en: "Phone Number", ar: "رقم الهاتف" },
  lblMyAddresses: { en: "My Addresses", ar: "عناويني" },
  lblHomeAddress: { en: "Home", ar: "المنزل" },
  lblNoSavedAddress: { en: "No saved address yet", ar: "لا يوجد عنوان محفوظ بعد" },
  lblDefault: { en: "Default", ar: "افتراضي" },
  lblAccountSettings: { en: "Account Settings", ar: "إعدادات الحساب" },
  lblNotifications: { en: "Notifications", ar: "الإشعارات" },
  lblOrderDeliveryUpdates: { en: "Order & Delivery Updates", ar: "تحديثات الطلب والتوصيل" },
  lblOrderDeliveryUpdatesDescription: {
    en: "Get notified about order status changes",
    ar: "احصل على إشعارات عند تغير حالة الطلب",
  },
  lblPromotionsOffers: { en: "Promotions & Offers", ar: "العروض والتخفيضات" },
  lblPromotionsOffersDescription: {
    en: "Receive exclusive deals and discounts",
    ar: "استقبل العروض والخصومات الحصرية",
  },
  lblSmsNotifications: { en: "SMS Notifications", ar: "إشعارات الرسائل النصية" },
  lblSmsNotificationsDescription: {
    en: "Instant updates via text message",
    ar: "تحديثات فورية عبر الرسائل النصية",
  },
  lblEnabled: { en: "Enabled", ar: "مفعل" },
  lblDisabled: { en: "Disabled", ar: "معطل" },
  lblWishlistChocolateCake: { en: "Chocolate Fudge Cake (1 kg)", ar: "كيكة فادج الشوكولاتة (1 كجم)" },
  lblWishlistButterCookies: { en: "Butter Cookies Box", ar: "علبة كوكيز بالزبدة" },

  lblHomeEidSpecial: { en: "Eid Special", ar: "عروض العيد" },
  lblHomeBestSellers: { en: "Best-Sellers", ar: "الأكثر مبيعاً" },
  lblAddToCart: { en: "Add to Cart", ar: "أضف إلى السلة" },
  lblWhyOrderOnline: {
    en: "Why You Should Order Online With Us?",
    ar: "لماذا تطلب أونلاين من عندنا؟",
  },
  lblPersonalizedCake: { en: "Personalized Cake", ar: "كيك مخصص" },
  lblOverHundredDesigns: { en: "(Over 100 Designs)", ar: "(أكثر من 100 تصميم)" },
  lblEasyOrdering: { en: "Easy Ordering", ar: "طلب سهل" },
  lblWithinTwoMinutes: { en: "(Within 2 Minutes)", ar: "(خلال دقيقتين)" },
  lblFastDelivery: { en: "Fast Delivery", ar: "توصيل سريع" },
  lblWithinTwoHours: { en: "(Within 2 hours)", ar: "(خلال ساعتين)" },
  lblByOccasions: { en: "By Occassions", ar: "حسب المناسبات" },
  lblByCategories: { en: "By Categories", ar: "حسب الفئات" },
  lblCategoryCakes: { en: "Cakes", ar: "الكيك" },
  lblCategoryCookies: { en: "Cookies", ar: "الكوكيز" },
  lblMoreGiftOptions: { en: "More gift options", ar: "خيارات هدايا أكثر" },
  lblMoreGiftDescription: {
    en: "Explore more ice cream creations & surprise your beloved with personalized messages",
    ar: "اكتشف المزيد من ابتكارات الآيس كريم وفاجئ أحبائك برسائل مخصصة",
  },
  lblViewIceCreamCollections: { en: "VIEW ICE CREAM COLLECTIONS", ar: "عرض مجموعة الآيس كريم" },
  lblMakeCookiesBox: { en: "Make your own cookies box!", ar: "اصنع علبة الكوكيز الخاصة بك!" },
  lblMakeCookiesBoxDescription: {
    en: "Fresh, high-quality ingredients and baked to perfection. Assemble your own box of cookies to create the perfect mix of flavors for you or your friends and family.",
    ar: "مكونات طازجة وعالية الجودة ومخبوزة بإتقان. كوّن علبة الكوكيز الخاصة بك لتصنع مزيج النكهات المثالي لك أو لأصدقائك وعائلتك.",
  },
  lblMakeYourOwnBox: { en: "MAKE YOUR OWN BOX", ar: "اصنع علبتك الخاصة" },
  lblPrevious: { en: "Previous", ar: "السابق" },
  lblNext: { en: "Next", ar: "التالي" },
};
